version: '3.3'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 80:8000
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - ./data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
